/*
F IZUSVR1,DISPLAY IZU
+CWWKB0004I: z/OSMF PARMLIBs DISPLAY
IZUG013I The home page of z/OSMF server in SYSTEM(SY1)
in AUTOSTART_GROUP(IZUDFLT) can be accessed at :
https://XXXXXX.XXX.XXX:443/zosmf
IZUG014I The server started at
and has been running for 0004(hhhh):424681(mm):02(ss)
Current z/OSMF settings
Source
HOSTNAME(XXXXXX.XXX.XXX)
IZUPRM3S
HTTP_SSL_PORT(443)
IZUPRM3S
LOGGING('*=warning:com.ibm.zoszmf.*=info:com.ibm.zoszm
f.environment.ui=finer')
IZUPRM3S
UNAUTH_USER(IZUGUEST)
IZUPRM3S
SEC_GROUPS
ADMIN(IZUADMIN)
IZUPRM3S
USER(IZUUSER)
IZUPRM3S
SECADMIN(IZUSECAD)
IZUPRM3S
SAF_PREFIX(IZUDFLT)
IZUPRM3S
CLOUD_SAF_PREFIX(IYU)
IZUPRM3S
KEYRING_NAME(IZUKeyring.IZUDFLT)
IZUPRM3S
SESSION_EXPIRE(495)
IZUPRM3S
WLM_CLASSES
LONG_WORK(IZUGWORK)
IZUPRM3S
DEFAULT(IZUGHTTP)
IZUPRM3S
JAVA_HOME(/usr/lpp/java/J8.0_64)
IZUPRM3S
TEMP_DIR(/tmp)
IZUPRM3S
INCIDENT_LOG UNIT(SYSALLDA)
IZUPRM3S
RESTAPI_FILE
ACCT(IZUACCT)
IZUPRM3S
PROC(IZUFPROC)
IZUPRM3S
REGION(65536)
IZUPRM3S
COMMON_TSO
ACCT(IZUACCT)
IZUPRM3S
PROC(IZUFPROC)
IZUPRM3S
REGION(50000)
IZUPRM3S
AUTOSTART_GROUP(IZUDFLT)
IZUPRM3S
AUTOSTART(LOCAL)
IZUPRM3S
SERVER_PROC(IZUSVR1)
IZUPRM3S
ANGEL_PROC(IZUANG1)
IZUPRM3S
USER_DIR(/var/zosmf)
IZUPRM3S
CSRF_SWITCH(ON)
IZUPRM3S
Status of z/OSMF plugins
Configuration Assistant(STARTED)
IZUPRM3S
Capacity Provisioning(STARTED)
IZUPRM3S
Workload Management(STARTED)
IZUPRM3S
Resource Monitoring(STARTED)
IZUPRM3S
Incident Log(STARTED)
IZUPRM3S
Software Management(STARTED)
IZUPRM3S
WebISPF(STARTED)
IZUPRM3S
Sysplex Management(STARTED)
IZUPRM3S
+CWWKB0005I: COMMAND RESPONSES COMPLETED SUCCESSFULLY FROM display izu
348
Command Handler.
+CWWKB0002I: MODIFY COMMAND DISPLAY IZU COMPLETED SUCCESSFULLY.
*/
options scientific by signal arg parse
call digits
push source
exit
